# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js: stable

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - wq_blog

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境和主题，这里的主题就是原来修改过的主题，我将其托管到另一个github仓库，直接clone就行，否则每次都是新的主题，要重新设置。
before_install:
  - npm install -g hexo-cli
  #- git clone https://github.com/smduan/next.git themes/next

##安装git插件和搜索功能插件
install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-searchdb --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "wqwangchn"
  - git config user.email "wqwangchn@163.com"
  - git add .
  - git commit -m "Travis CI AutoUpdate"
  - git push --force --quiet "https://${hexo_token}@${GITHUB_REF}" master

env:
  global:
    - GITHUB_REF: github.com/wqwangchn/wqwangchn.github.io.git
